### ISSUE TITLE
oh no

### ISSUE THREAD

**Issue by Shizophrener** [SpEZiiL/speziil.github.io#1]
A problem has been detected and Windows has been shut down to prevent damage to your computer.

If this is the first time you've seen this stop error screen, restart your computer. if this screen appears again, follow these steps:

Check to make sure any new hardware or software is properly installed. I this is a new installation, ask your hardware or software manufacturer for and Windows updates you might need.

If problems continue, disable or remove any newly installed hardware or software. Disable BIOS memory options such as caching or shadowing. If you need to use Safe Mode to remove or disable components, restart your computer, press F8 to select Advanced Startup Options, and then select Safe Mode.

**Comment by SpEZiiL** [comment]
![when you walking](https://pics.me.me/when-you-walking-27690577.png)
